### ISSUE TITLE
error in RSI indicator

### ISSUE THREAD

**Issue by peymanvh** [twopirllc/pandas-ta#184] opened 2021-01-06 07:52 UTC
I have problem with pandas ta
After run this statement
dp.ta.rsi(dp['close'],length=14)
error show this one
TypeError: rsi() got multiple values for argument 'length'
version of pandas ta is 0.2.23b
please help me to solve my problem
thanks

**Comment by YuvalWein** [comment] 2021-01-06 08:29
Hi peymanvh,
Check this snippet of code:
```python
import pandas_ta as ta
import yfinance as yf
msft = yf.Ticker("MSFT")
hist = msft.history(period="1y")
ta.rsi(hist['Close'], length=14)
```
Is the problem occurs also with this code?
What happens if you delete the 'dp' at the beginning of your code?

<b>dp</b>.ta.rsi(dp['close'],length=14)

**Comment by twopirllc** [comment] 2021-01-06 17:00
Hello @peymanvh,

Thanks for using Pandas TA. It appears that your Pandas DataFrame is called ```dp```. There are two simple ways to get what you need. I would pick one way or the other, either the **Conventional** or **DataFrame Extension** style.

## Conventional Use (Like TA Lib)
```python
dp = # your DataFrame
rsi14 = ta.rsi(dp['close']) # By default, the length is 14
print(rsi14)
```
**OR** if you want to manually append RSI to your DataFrame
```python
dp = # your DataFrame
dp['RSI14'] = ta.rsi(dp['close']) # By default, the length is 14
print(dp)
```

## DataFrame Extension
The DataFrame Extension automatically uses the default series of the indicator, 'close' in this case.
```python
dp = # your DataFrame
rsi14 = dp.ta.rsi()
print(rsi14)
```

**OR** if you want to manually append RSI to your DataFrame
```python
dp = # your DataFrame
dp['RSI14'] = dp.ta.rsi()
print(dp)
```

**OR** if you want to automatically append RSI to your DataFrame
```python
dp = # your DataFrame
dp.ta.rsi(append=True)
print(dp)
```

Also, use the ```length``` parameter if you need a length different from it's default value. For more information about an indicator, use ```help(ta.rsi)```.

Thanks @YuvalWein for also providing an example that will work.

Hope this helps and please let us know if this works for you.

Thanks,
KJ

**Comment by twopirllc** [comment] 2021-01-12 21:59
Hello @peymanvh,

Since you have not responded at all, I assume @YuvalWein and I have provided enough information to help you use the **rsi** indicator. If you do not respond within a couple of days, I will be closing this Issue.

Best Regards,
KJ

**Closed** 2021-01-15 17:05 UTC
Labels: info

**Comment by Stone321284** [comment] 2024-10-19 23:02
Hello Kelvin(twopirllc), I think you don't understand peymanvh's question:
he  has a  problem with pandas ta
After run this statement
dp.ta.rsi(dp['close'],length=14)
error show this one
TypeError: rsi() got multiple values for argument 'length'.

Obviously, he has already 100% followed your way to call up the function RSI. 
But the problem is: it gets  error " multiple values for argument 'length'", he don't know why such error is occuring.
How to fix it?  That's his question.    
But you answer him: how to call up pandas-ta function, obviously he knows it.    
I also have the same question when I am calling up the function kama, it also occures a error:
**kama() got multiple values for argument 'length'.**
The below is my code:

data1['KAMA5']= data1.ta.kama(data1['closePrice'], length=5)
data1['KAMA10']=data1.ta.kama(data1['closePrice'], length=10)

could you please help to support how to fix this error?

Thank you very much.

**Comment by twopirllc** [comment] 2024-10-22 15:35
Hello @Stone321284 ,

1. Upgrade to the _developemnt_ version if you have not already.
2. Also, let's not piggyback on such an old issue... please fill out a seperate [Issue](https://github.com/twopirllc/pandas-ta/issues/new/choose)

Kind Regards,
KJ
