### ISSUE TITLE
Study's failing when ta kind doesn't have enough data

### ISSUE THREAD

**Issue by andrewkenreich** [twopirllc/pandas-ta#520] opened 2022-04-21 17:47 UTC
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
latest dev branch

**Do you have _TA Lib_ also installed in your environment?**
yes

**Describe the bug**
When running a Study 

**To Reproduce**

Use a dataframe that only has 10-30 rows of data and run the below.
```python
MyStudy = ta.Study(
            name="DCSMA10",
            description="SMA 50,200, BBANDS, RSI, MACD and Volume SMA 20",
            cores=0,
            ta=[
                {"kind": "sma", "length": 20},
                {"kind": "sma", "length": 50},
                {"kind": "sma", "length": 100},
                {"kind": "sma", "length": 200},
                {"kind": "ema", "length": 12},
                {"kind": "ema", "length": 26},
                {"kind": "ema", "length": 50},
                {"kind": "ema", "length": 200},
                {"kind": "macd", "fast": 12, "slow": 26, "signal": 9},
                {"kind": "rsi", "length": 14},
                {"kind": "percent_return", "length": 5},
                {"kind": "percent_return", "length": 20},
                {"kind": "percent_return", "length": 50},
            ],
        )
        # Run it
        df = df.ta.study(MyStudy, returns=True)
```

**Expected behavior**
Would expect this to just not put a column and skip that ta in the DF but it errors out with the below.

```sh
File ~/anaconda3/envs/obb_api/lib/python3.9/site-packages/pandas_ta/core.py:731, in AnalysisIndicators.study(self, *args, **kwargs)
    729         for ind in ta:
    730             params = ind["params"] if "params" in ind and isinstance(ind["params"], tuple) else tuple()
--> 731             getattr(self, ind["kind"])(*params, **{**ind, **kwargs})
    732 else:
    733     if Imports["tqdm"] and verbose:

File ~/anaconda3/envs/obb_api/lib/python3.9/site-packages/pandas_ta/core.py:1003, in AnalysisIndicators.macd(self, fast, slow, signal, offset, **kwargs)
   1001 def macd(self, fast=None, slow=None, signal=None, offset: Int = None, **kwargs: DictLike):
   1002     close = self._get_column(kwargs.pop("close", "close"))
-> 1003     result = macd(close=close, fast=fast, slow=slow, signal=signal, offset=offset, **kwargs)
   1004     return self._post_process(result, **kwargs)

File ~/anaconda3/envs/obb_api/lib/python3.9/site-packages/pandas_ta/momentum/macd.py:64, in macd(close, fast, slow, signal, talib, offset, **kwargs)
     62     macd, signalma, histogram = MACD(close, fast, slow, signal)
     63 else:
---> 64     fastma = ema(close, length=fast, talib=mode_tal)
     65     slowma = ema(close, length=slow, talib=mode_tal)
     67     macd = fastma - slowma

File ~/anaconda3/envs/obb_api/lib/python3.9/site-packages/pandas_ta/overlap/ema.py:82, in ema(close, length, talib, presma, offset, **kwargs)
     80         sma_nth = close[0:length].mean()
     81         close[:length - 1] = nan
---> 82         close.iloc[length - 1] = sma_nth
     83     ema = close.ewm(span=length, adjust=adjust).mean()
     85 # Offset

File ~/anaconda3/envs/obb_api/lib/python3.9/site-packages/pandas/core/indexing.py:720, in _LocationIndexer.__setitem__(self, key, value)
    718     key = com.apply_if_callable(key, self.obj)
    719 indexer = self._get_setitem_indexer(key)
--> 720 self._has_valid_setitem_indexer(key)
    722 iloc = self if self.name == "iloc" else self.obj.iloc
    723 iloc._setitem_with_indexer(indexer, value, self.name)

File ~/anaconda3/envs/obb_api/lib/python3.9/site-packages/pandas/core/indexing.py:1461, in _iLocIndexer._has_valid_setitem_indexer(self, indexer)
   1459 elif is_integer(i):
   1460     if i >= len(ax):
-> 1461         raise IndexError("iloc cannot enlarge its target object")
   1462 elif isinstance(i, dict):
   1463     raise IndexError("iloc cannot enlarge its target object")

IndexError: iloc cannot enlarge its target object
```

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment] 2022-05-02 23:10
Hey @andrewkenreich,

Please try out the new _development_ branch and see if it's working better.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by twopirllc** [comment] 2022-05-22 21:58
@andrewkenreich,

Closing till you can confirm that the latest _development_ branch is working as intended.

Thanks,
KJ

**Closed by twopirllc** 2022-05-22 21:58 UTC
Labels: bug
