### ISSUE TITLE
Enable df.ta.strategy("All") to produce indicators with randomized lengths (and other values)

### ISSUE THREAD

**Issue by sword134** [twopirllc/pandas-ta#238] opened 2021-03-03 16:26 UTC
Hello,
I've been using the library for many months now and its great! However for ML practitioners it would be nice if the df.ta.strategy("All") had a parameter to enable it to create indicators with randomized values. That way we can have 2, 3, 4, 5x the columns of the same indicators but with different input lengths and other values.

**Comment by twopirllc** [comment] 2021-03-06 00:14
Hello @sword134,

> I've been using the library for many months now and its great! 

I am glad you find it useful. Thank you!

Apologies for the delay. I wanted to look into the Issue prior to responding.

> However for ML practitioners it would be nice if the df.ta.strategy("All")

I can understand the use of "All" for ML practitioners. Yet personally, I do not recommend using "All" for ML as there are several indicators once normalized become correlated and redundant. But that's my opinion... worth a grain of salt.

I am hesitant in enhancing ```df.ta.strategy()``` unless absolutely necessary. Additionally, ```df.ta.strategy("All")``` creates well over 180+ columns and more to come as I try to minimally cover TA Lib indicators and other brokerage indicators.

In attempt to find a work around _and_ not muck with ```df.ta.strategy("All")``` even more, I will push an update that will allow you to do the following:

```python
import pandas as pd
import pandas_ta as ta

df = # ohlcv
[df.ta.strategy("All", length=_) for _ in range(5, 11)]
```

Allowing this functionality has exposed a few **bugs** I need to squash first but should be available on the **development** branch sometime next week if that works. I'll let you know.

<br/>

Furthermore, there is a lesser know method of targeting indicator arguments using a Custom Strategy. I recommend moving to a Custom Strategy once you narrow down your feature set. 

```python
import pandas as pd
import pandas_ta as ta

df = # ohlcv
# df.ta.cores = 0 # Uncomment to see if you get a speed boost

custom_args_ta = [
    {"kind": "ema", "params": (10,)},
    {"kind": "ema", "params": (50,)},
    {"kind": "sma", "params": (200,)},
    {"kind": "bbands", "params": (10, 2)} 
]

custom = ta.Strategy(
    "Custom Args Tuple",
    custom_args_ta,
    "Allow for easy filling in indicator arguments by argument placement."
)
df.ta.strategy(custom)
```

<br/>

Lastly, perhaps [Tune TA](https://github.com/jmrichardson/tuneta) may be helpful in your quest. 🤷🏼‍♂️ 

_"TuneTA optimizes a broad set of technical indicators to maximize its correlation to a user defined target variable. The set of tuned indicators can be reduced by choosing the most correlated with the target while minimizing correlation with each other. TuneTA maintains its state to add each tuned indicator to multiple data sets (train, validation, test)."_

Thoughts?

Kind Regards,
KJ

**Comment by sword134** [comment] 2021-03-06 11:22
@twopirllc fantastic news. This is much appriciated!

**Comment by twopirllc** [comment] 2021-03-11 17:54
Hello @sword134,

I have a _Development Version_ to test to make sure it works as intended. Run:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

If you want to go back to the **Latest Version**. Version: *0.2.45b* Run:
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Please let me know what your think when you get a chance.

Thanks,
KJ

**Closed** 2021-04-17 16:03 UTC
Labels: enhancement
