### ISSUE TITLE
PSAR indicator - Incorrect value 

### ISSUE THREAD

**Issue by mtvu** [twopirllc/pandas-ta#180] opened 2021-01-01 10:17 UTC
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
```python
import pandas_ta as ta
print(ta.version)
```
0.2.28b0

**Upgrade.**
```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

**Describe the bug**
The value of PSAR seems incorrect (as compared to TradingView). 

 
--
Pandas_ta for 2020-12-31
PSARs_0.02_0.2 = 377.265728 
TradingView for 2020-12-31
PSAR = 363.67

**To Reproduce**
Provide sample code.
```python
from pandas_datareader import data
from IPython.display import display, HTML
import pandas as pd
import datetime
import pandas_ta as ta

start = datetime.datetime(2020, 1, 1)
end = datetime.datetime.now()
ticker = "SPY"
df = data.DataReader(ticker, 
                       start=start, 
                       end=end, 
                       data_source='yahoo')
df.ta.psar(append=True)
display(HTML(df.sort_index(ascending=False).to_html()))
```
**Expected behavior**
The value of PSAR should be as close as possible to TradingView
**Screenshots**

**Additional context**

Thanks for using Pandas TA!

**Comment by twopirllc** [comment] 2021-01-01 18:23
Hello @mtvu,

Happy New Year! Hope all is well.

Yeah, the one off value does not look good in comparison with TradingView.
> Pandas_ta for 2020-12-31: PSARs_0.02_0.2 = 377.265728
> TradingView for 2020-12-31: PSAR = 363.67

## TradingView PSAR

Tuning Parabolic SAR with TradingView (TV) is a blackbox reverse engineering case with no insight to their implementation. TV shares some of their internal indicators in their code or in their help system, but unfortunately not in this case.

<img width="1311" alt="Screen Shot 2021-01-01 at 9 54 06 AM" src="https://user-images.githubusercontent.com/18198392/103443794-62c57a80-4c17-11eb-9807-c9476612684d.png">

<br/>

## TA Lib Correlation

Also **TA Lib** is still the _de facto_ library that many base accuracy on, thus I develop indicators to be as closely correlated with it as possible. Currently **psar** is 99.94% correlated with __TA Lib__, so the minimum standard has been achieved. Below is the correlation results versus **TA Lib**.

<img width="531" alt="Screen Shot 2021-01-01 at 10 01 38 AM" src="https://user-images.githubusercontent.com/18198392/103443919-7f15e700-4c18-11eb-96c5-10ae77b0ad16.png">


## TV vs PandasTA Indicator Correlation How To

I recommend following the steps laid out in Issue #107 on how to export data from TV and run a correlation test with TV indicators versus Pandas TA indicators. I am interested in the correlation results compared to the final result you mentioned above.


## TV Implementation

While this library primarily aims to be correlated with **TA Lib** first and foremost, I do welcome versions from other sources (including TV) just like I did with **squeeze** indicator. If you are willing to give a crack at creating a TV version, that would be awesome and I assume many others would appreciate it as well. If so, fork this repo, make the additions and submit a PR.

<br/>

Hopefully the correlation accuracy with **TA Lib** convinces you that there is no major accuracy issues with **psar** and that differences among the many platforms do occur but can be implemented in Pandas TA. Unfortunately TV does not make it easy for this case.

Hope this helps!

Thanks,
KJ

**Comment by rahulmr** [comment] 2021-01-02 08:49
@twopirllc I think [this](https://python-tradingview-ta.readthedocs.io/en/latest/how_it_works.html) might be helpful.

**Comment by twopirllc** [comment] 2021-01-02 17:28
@rahulmr,

Thanks for the suggestion, unfortunately that package web scrapes TV's website with base url ```https://scanner.tradingview.com/{screener}/scan```. Then they reversed engineered the JS Recommendation signals into Python. Usually, TV provides the source code for their internal indicators but not in this case 😞 .

The other avenue is to go through user shared PSAR code that is viewable and compare it with TV's ```sar```. Make sure they are correlated and then adapt that user's implementation. Reverse by proxy. 🤷🏼‍♂️ 

KJ

**Comment by twopirllc** [comment] 2021-01-12 22:18
Hello @mtvu,

I assume by no response, I was able to convince you on the accuracy of **psar**. If not, please let me know and I will draft up a correlation analysis between TradingView and Pandas TA as soon as I can. If do not hear from you in a couple of days, I will be closing this Issue.

Kind Regards,
KJ

**Comment by mtvu** [comment] 2021-01-13 07:00
Hi @twopirllc 
My plan is to generate the PSAR using the ta-lib for a few stocks and see the correlation myself. I have not been able to do that yet. 
Another option is to get the PSAR for Alpha Vantage and cross check as well. I guess the tricky bit is to determine what is the source of truth. I'm interested it if we could at least check the PSAR generated by AlphaVantage.

**Comment by mtvu** [comment] 2021-01-13 08:36
I managed to run the test. The results are as follows 
 PTA-PSAR = Pandas-Ta
 TALIB-PSAR = ta-lib
SAR = Alpha Vantage PSAR
Diff-A = Diff between PTA-PSAR and TALIB-PSAR
Diff-B = Diff between PTA-PSAR and SAR
adj_close | PTA-PSAR | TALIB-PSAR | SAR | Diff-A | Diff-B
-- | -- | -- | -- | -- | --

378.769989 | 367.499676 | 367.243770 | 365.180400 | 0.000696 | 0.006311
378.690002 | 366.606678 | 366.334436 | 364.139300 | 0.000743 | 0.006730
381.260010 | 365.656679 | 365.367061 | 363.031800 | 0.000792 | 0.007179
379.100006 | 365.063207 | 364.761522 | 362.329000 | 0.000826 | 0.007490
373.549988 | 364.820007 | 364.481961 | 362.030000 | 0.000927 | 0.007648
371.329987 | 376.552173 | 364.196695 | 376.293300 | 0.032812 | 0.000687
368.790009 | 377.041013 | 363.905608 | 376.584400 | 0.034838 | 0.001211
373.880005 | 377.265728 | 363.608579 | 376.881400 | 0.036200 | 0.001019
371.989990 | 377.495028 | 363.305489 | 377.184500 | 0.037589 | 0.000823
371.459991 | 377.729008 | 362.996214 | 377.493800 | 0.039004 | 0.000623
372.170013 | 377.967764 | 362.680626 | 377.809400 | 0.040446 | 0.000419
369.000000 | 378.211392 | 362.358599 | 378.131400 | 0.041915 | 0.000211
367.570007 | 378.459991 | 362.029999 | 378.460000 | 0.043413 | 0.000000
367.239990 | 378.459991 | 362.029999 | 378.460000 | 0.043413 | 0.000000
367.859985 | 367.019989 | 362.029999 | 378.460000 | 0.013596 | 0.031170
369.179993 | 372.459991 | 372.459991 | 365.467200 | 0.000000 | 0.018775





Code to produce the result 
```
import requests
import pandas as pd
import pandas_ta as ta
import yfinance as yf
import talib
pd.set_option('display.float_format', lambda x: '%.6f' % x)
data = yf.download(tickers='SPY', period='1y')
data.ta.psar(append=True)

# Calculate PSAR using talib
data['TALIB-PSAR'] = talib.SAR(data.high, data.low, acceleration=0.02, maximum=0.2)
data['PTA-PSAR'] =  data['PSARl_0.02_0.2'].combine_first(data['PSARs_0.02_0.2'])

ta_df = data[['adj_close','PTA-PSAR', 'TALIB-PSAR' ]].sort_index(ascending=False).head(50)

# Get PSAR data from AV
url = f"https://www.alphavantage.co/query?function=SAR&symbol=SPY&interval=daily&acceleration=0.02&maximum=0.2&apikey=<AV API Key>"
response = requests.get(url)
response_dict = response.json()
_, header = response.json()

av_df = pd.DataFrame.from_dict(response_dict[header], orient='index').sort_index(ascending=False).head(50)


result_df = ta_df.join(av_df)
result_df['SAR'] = result_df['SAR'].astype('float64') 

result_df['Diff-A'] = abs(result_df['PTA-PSAR'] -  result_df['TALIB-PSAR'])/result_df['PTA-PSAR'] 
result_df['Diff-B'] = abs(result_df['PTA-PSAR'] -  result_df['SAR'])/result_df['PTA-PSAR']

**Comment by mtvu** [comment] 2021-01-13 08:51
I guess the differences could be attributed to data used for the calculation ( i.e. yahoo data vs whatever data used by AV)

**Comment by twopirllc** [comment] 2021-01-14 17:33
Hi @mtvu,

Yes. The Data Source matters. TradingView (TV) and AlphaVantage (AV) are likely to have differing ohlcv values at various points. So the PSAR values are going to deviate to some degree. In regards to AV, based on the naming of the TA they provide it appears they use TA Lib behind the scenes.

I use a correlation test to test the accuracy between two indicators. For example when I want to test Pandas TA vs TV, I do the following steps:
1. Load TV and PSAR on a chart
1. Then _Export Chart Data_ and set Time Format to ISO
   a. rename the columns for easy identification
1. Read csv in a Jupyter Notebook
1. Append Pandas TA PSAR to DataFrame
   a. Drop unnecessary columns: ohlcv et al 
1. Run ```dd.corr()``` for the correlation results.

Similarily if you want to compare with AV etc.

I will post my AV and TV PSAR correlation results later. I am still catching up on Issues while trying to get my new development laptop up and running.

Thanks,
KJ

**Comment by twopirllc** [comment] 2021-01-22 21:27
Hello @mtvu,

You are correct. Upon review of Pandas TA **psar**, it does appear to deviate from not only TradingView (TV) but also TA Lib (TAL). But it is only recently that it has deviated.

<img width="758" alt="Screen Shot 2021-01-22 at 1 12 41 PM" src="https://user-images.githubusercontent.com/18198392/105547647-8d08d600-5cb3-11eb-833c-5694d68835eb.png">

It was inline with TV up until 12/18/2020 - 1/5/2021 and mysteriously when above. 🤷🏼‍♂️ 

<img width="758" alt="Screen Shot 2021-01-22 at 1 18 09 PM" src="https://user-images.githubusercontent.com/18198392/105548327-54b5c780-5cb4-11eb-859f-faca60234e93.png">

Anyhow, I have marked this as a **bug** and rework the code. Since TV will not show their SAR code, I will be aiming to keep it correlated with TAL.

I apologize for the delay on working on this. I have been busy with moving to a new development computer, taking care of pending PRs and family issues.

Kind Regards,
KJ

**Comment by AxelGUILLAUMET** [comment] 2021-06-07 23:37
Hi there! Same problem for me, I had some incoherents with PSAR...

![9b7d22bb-0889-4820-bb85-49a50626b9d8](https://user-images.githubusercontent.com/47301337/121100394-5e514f00-c7bf-11eb-9c95-7cc5677fe1f7.jpg)
![efd83e54-be78-4b96-9fae-6ac9401d4f21](https://user-images.githubusercontent.com/47301337/121100396-5ee9e580-c7bf-11eb-933d-05149a8e8e8c.jpg)

I'm looking for a fix for that... If I have something I report there!

Cheers!

**Comment by AxelGUILLAUMET** [comment] 2021-06-08 04:17
https://www.tradinformed.com/calculate-psar-indicator-revised/

**Comment by twopirllc** [comment] 2021-06-08 23:03
Hello @AxelGUILLAUMET,

Thanks for sharing.

Kind Regards,
KJ

**Comment by AbyssAlora** [comment] 2021-06-10 15:54
Hello,
I've tried reproduce TV psar from chart today, but i put there no more than half of hour. I wrote code in different language but here is python version (hope that it's ok). This code produced similar results to TV on some live tests, but I have no time to test it properly. Maybe it's help, but I think that definition of psar is slightly different.

```python
def psar(high, low, af=0.02, af_max=0.2):
    falling = True
    sar = high[0]
    ep = low[0]
    af0 = af

    psar_l = [0] * len(high)
    psar_s = [0] * len(high)

    for row in range(1, len(high)):
        HIGH = high[row]
        LOW = low[row]

        if falling:
            if LOW < ep:
                ep = LOW
                af = min(af + af0, af_max)
    
            new_sar = sar + af * (ep - sar)
            new_sar = max(HIGH, new_sar)
    
            reverse = HIGH > sar
        else: 
            if HIGH > ep:
                ep = HIGH
                af = min(af + af0, af_max)
    
            new_sar = sar + af * (ep - sar)
            new_sar = min(LOW, new_sar)
    
            reverse = LOW < sar

        if reverse:
            new_sar = ep
            af = af0
            falling = not falling
    
            if falling:
                ep = LOW
            else:
                ep = HIGH

        sar = new_sar

        if not falling:
            psar_l[row] = sar
        else:
            psar_s[row] = sar

    return psar_l, psar_s
```

Let me know if there are some incorrections and I'll take a look.

Best regards,
AA

**Comment by twopirllc** [comment] 2021-06-10 18:53
Hello @AbyssAlora,

Great! I check it out when I can.

Also, are you able to export data from TV and do a correlation test as outlined in Issue #107? If so, that would also be helpful.

Kind Regards,
KJ

**Comment by AbyssAlora** [comment] 2021-06-11 07:17
Hi @twopirllc,
I've made some changes as well as I've done some correlation tests, but I have no idea if it's enough. 

Code: 
```python
def psar(high, low, close=None, af=None, max_af=None, offset=None, **kwargs):
    """Indicator: Parabolic Stop and Reverse (PSAR)"""
    # Validate Arguments
    high = verify_series(high)
    low = verify_series(low)
    af = float(af) if af and af > 0 else 0.02
    max_af = float(max_af) if max_af and max_af > 0 else 0.2
    offset = get_offset(offset)

    falling = True
    sar = high.iloc[0]
    ep = low.iloc[0]
    af0 = af

    if close is not None:
        close = verify_series(close)
        sar = close.iloc[0]

    long = Series(npNaN, index=high.index)
    short = long.copy()
    reversal = Series(False, index=high.index)
    _af = long.copy()
    _af.iloc[0:2] = af0

    m = high.shape[0]

    # Calculate Result
    for row in range(2, m):
        HIGH = high.iloc[row]
        LOW = low.iloc[row]

        if falling:
            new_sar = sar + af * (ep - sar)

            if LOW < ep:
                ep = LOW
                af = min(af + af0, max_af)

            new_sar = max(high.iloc[row - 1], high.iloc[row - 2], new_sar)

            reverse = HIGH > sar + af * (ep - sar)
        else:
            new_sar = sar + af * (ep - sar)

            if HIGH > ep:
                ep = HIGH
                af = min(af + af0, max_af)

            new_sar = min(low.iloc[row - 1], low.iloc[row - 2], new_sar)

            reverse = LOW < sar + af * (ep - sar)

        if reverse:
            new_sar = ep
            af = af0
            falling = not falling

            if falling:
                ep = LOW
            else:
                ep = HIGH

        sar = new_sar

        if not falling:
            long.iloc[row] = sar
        else:
            short.iloc[row] = sar

        _af.iloc[row] = af
        reversal.iloc[row] = reverse

    # Offset
    if offset != 0:
        _af = _af.shift(offset)
        long = long.shift(offset)
        short = short.shift(offset)
        reversal = reversal.shift(offset)

    # Handle fills
    if "fillna" in kwargs:
        _af.fillna(kwargs["fillna"], inplace=True)
        long.fillna(kwargs["fillna"], inplace=True)
        short.fillna(kwargs["fillna"], inplace=True)
        reversal.fillna(kwargs["fillna"], inplace=True)
    if "fill_method" in kwargs:
        _af.fillna(method=kwargs["fill_method"], inplace=True)
        long.fillna(method=kwargs["fill_method"], inplace=True)
        short.fillna(method=kwargs["fill_method"], inplace=True)
        reversal.fillna(method=kwargs["fill_method"], inplace=True)

    # Prepare DataFrame to return
    _params = f"_{af0}_{max_af}"
    data = {
        f"PSARl{_params}": long,
        f"PSARs{_params}": short,
        f"PSARaf{_params}": _af,
        f"PSARr{_params}": reversal,
    }
    psardf = DataFrame(data)
    psardf.name = f"PSAR{_params}"
    psardf.category = long.category = short.category = "trend"

    return psardf
```
**Should be reviewd.**

Tests:
```python
data = pd.read_csv("1.csv")  # Read exported 1m data from TV with ParabolicSAR
tv_psar = data['ParabolicSAR'].values

psar = data.ta.psar(fillna=0)
ta_psar = psar['PSARl_0.02_0.2'].values + psar['PSARs_0.02_0.2'].values

psarDf = pd.DataFrame({
    'psar_tv': tv_psar[10:],  # Ignore first first few values because of self correction
    'psar_ta': ta_psar[10:],  # Ignore first first few values because of self correction
})

print(psarDf.tail(20))
print(psarDf.corr(method='pearson'))
```

Results:
```
       psar_tv   psar_ta
5816  1.543524  1.543524
5817  1.543254  1.543254
5818  1.542988  1.542988
5819  1.542729  1.542729
5820  1.542120  1.542120
5821  1.541212  1.541212
5822  1.540360  1.540360
5823  1.539558  1.539558
5824  1.538805  1.538805
5825  1.538096  1.538096
5826  1.537161  1.537161
5827  1.536300  1.536300
5828  1.535040  1.535040
5829  1.533906  1.533906
5830  1.532609  1.532609
5831  1.531468  1.531468
5832  1.530464  1.530464
5833  1.529580  1.529580
5834  1.528803  1.528803
5835  1.528118  1.528118
          psar_tv   psar_ta
psar_tv  1.000000  0.999972
psar_ta  0.999972  1.000000
```

Hope that's ok and helpful as well.

Kind regards,
AA

**Comment by twopirllc** [comment] 2021-06-11 20:43
Hello @AbyssAlora,

This is great! I really appreciate you taking the time to help resolve this Issue.

I believe it is enough. I will review and try out your code with from my end as well and check it's correlation. If it works out for me, would you be willing to try and make a PR and get some contribution credit? 😎   If not, no worries.

Thanks,
KJ

**Comment by AxelGUILLAUMET** [comment] 2021-06-12 15:34
Hi! I tested the new script (I modified PSAR.py into C:\Program Files\Python39\Lib\site-packages\pandas_ta\trend) And unfortunateñy the same false signal appears.

This is visble on LTO/USDT 5 MIN at 16:15 in UTC TIME.

![Error](https://user-images.githubusercontent.com/47301337/121781297-aaa6e100-cb69-11eb-9a99-cfdc426e7b22.PNG)
![Error2](https://user-images.githubusercontent.com/47301337/121781299-ab3f7780-cb69-11eb-880d-251ceb5b542a.PNG)

I hope I will have time later, I will try the excel example I send before. If i works I will adapt it to the lib...

**Comment by twopirllc** [comment] 2021-06-12 15:45
@AxelGUILLAUMET 

Make sure you are exporting both the data _and_ the **psar** indicator results to compare with Pandas TA's **psar** as described in Issue #107.

Thanks,
KJ

**Comment by AbyssAlora** [comment] 2021-06-12 17:00
Hi guys,

@AxelGUILLAUMET, I tested script that I post yesterday for LTOUSDT 5m exported from TV with parabolic sar. 

Results (~2k candles)
```
                     time   psar_tv   psar_ta
535  2021-06-07T15:05:00Z  0.250455  0.250455
536  2021-06-07T15:10:00Z  0.249837  0.249837
537  2021-06-07T15:15:00Z  0.246040  0.246040
538  2021-06-07T15:20:00Z  0.246109  0.246109
539  2021-06-07T15:25:00Z  0.246249  0.246249
540  2021-06-07T15:30:00Z  0.246384  0.246384
541  2021-06-07T15:35:00Z  0.246400  0.246400
542  2021-06-07T15:40:00Z  0.246400  0.246400
543  2021-06-07T15:45:00Z  0.247152  0.247152
544  2021-06-07T15:50:00Z  0.248125  0.248125
545  2021-06-07T15:55:00Z  0.249000  0.249000
546  2021-06-07T16:00:00Z  0.249788  0.249788
547  2021-06-07T16:05:00Z  0.250497  0.250497
548  2021-06-07T16:10:00Z  0.251136  0.251136
549  2021-06-07T16:15:00Z  0.256880  0.256880
550  2021-06-07T16:20:00Z  0.256765  0.256765
551  2021-06-07T16:25:00Z  0.256652  0.256652
552  2021-06-07T16:30:00Z  0.256541  0.256541
553  2021-06-07T16:35:00Z  0.251120  0.251120
554  2021-06-07T16:40:00Z  0.251253  0.251253
          psar_tv   psar_ta
psar_tv  1.000000  0.999921
psar_ta  0.999921  1.000000
```
Looks good from my side, but nobody knows if I'm right 😂. @twopirllc let me know about your tests and sure I'll be glad. 

AA

**Comment by AxelGUILLAUMET** [comment] 2021-06-13 03:05
Dear freinds, I made a little Python script to get all the results on a CSV file.

You can enter the time section you want in unix time.

```
# TEST PSAR
# Ver 0.1
# By Axel GUILLAUMET

################################
# API and ORDERS configuration #
################################

BINANCE_API_KEY = 'xxxxx' #Claves API
BINANCE_SECRET_KEY = 'xxxxx' #Clave SECRETA API


######################
# PARS CONFIGURATION #
######################

TRADE_FROM = 'USDT' #Divisa estable USDT EUR
TRADE_TO = 'LTO' #Divisa a tradear (ETH, BTC, ...)

#####################
# STRATEGY SETTINGS #
#####################

TRADE_TIMES = '5m'
SAMPLING_CANDLES_HISTORY = 1000 #Cuantos velas se agarran para calcular RSI || default 100

###################################
###################################

import ccxt
import pandas as pd
import time
import pandas_ta as ta
import signal

		
pd.set_option('display.max_rows', None)

import warnings
warnings.filterwarnings('ignore')

from datetime import datetime
import time

exchange = ccxt.binance({
    "apiKey": BINANCE_API_KEY,
    "secret": BINANCE_SECRET_KEY
})
			
def run():
    
    since = (1623024000 - 60*60) * 1000 # UTC timestamp in milliseconds
		
    bars = exchange.fetch_ohlcv(TRADE_CURRENCY, timeframe=TRADE_TIMES, since=since, limit=SAMPLING_CANDLES_HISTORY)		

    df = pd.DataFrame(bars, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
	
	
	#PSAR

    df_psar = ta.psar(df["high"],df["low"],df["close"])	

    CSV_OUT = open("out.csv", "a")	
		
    CSV_OUT.write(f'timestamp,open,high,low,close,volume,PSARl_0.02_0.2,PSARs_0.02_0.2,PSARaf_0.02_0.2,PSARr_0.02_0.2\n')
	
		
    for x in range(0, len(df.index)):
    #for x in range(len(df.index)-5, len(df.index)):
        print("{0}	{1}	{2}	{3}	{4}	{5}	{6}	{7}	{8}	{9}".format(df['timestamp'][x],df['open'][x],df['high'][x],df['low'][x],df['close'][x],df['volume'][x],df_psar['PSARl_0.02_0.2'][x],df_psar['PSARs_0.02_0.2'][x],df_psar['PSARaf_0.02_0.2'][x],df_psar['PSARr_0.02_0.2'][x]))
        CSV_OUT.write(f'{df["timestamp"][x]},{df["open"][x]},{df["high"][x]},{df["low"][x]},{df["close"][x]},{df["volume"][x]},{df_psar["PSARl_0.02_0.2"][x]},{df_psar["PSARs_0.02_0.2"][x]},{df_psar["PSARaf_0.02_0.2"][x]},{df_psar["PSARr_0.02_0.2"][x]}\n')
    CSV_OUT.close()
	 
	 
print('TEST PSAR - By Axel GUILLAUMET')

TRADE_CURRENCY = TRADE_TO+'/'+TRADE_FROM
      
run()
```
Then I attechaed there the CSV results with the 5m params 2021-06-07 @ 16H15 where the false signal PSAR appear with LTO/USDT as mentioned before.

Hope this can help... Having these datas in CSV I can prove the excel PSAR formula soon if it works... The problem is visible at line 209

[out.xlsx](https://github.com/twopirllc/pandas-ta/files/6643207/out.xlsx)

**Comment by AbyssAlora** [comment] 2021-06-13 07:15
Hi @AxelGUILLAUMET,

Here are two images. First one is your excel in compare with data exported directly from TV. Second one is part of chart from TV (LTOUSDT 5m). Looks like this is looking for a needle in a haystack. Are you sure that your comparison with graph is from the TV "spot market"? My question about that is because for example data in spot market and futures market are slightly different (you can find why for yourself). 

<img width="1115" alt="Screenshot 2021-06-13 at 08 47 41" src="https://user-images.githubusercontent.com/32155747/121798648-d12b5180-cc27-11eb-8814-22a134778193.png">
<img width="426" alt="Screenshot 2021-06-13 at 09 01 25" src="https://user-images.githubusercontent.com/32155747/121798652-d5576f00-cc27-11eb-947a-9ec4d0f3343f.png">


Besr regards,
AA

**Comment by twopirllc** [comment] 2021-06-13 17:15
@AbyssAlora & @AxelGUILLAUMET,

Sorry for the delay. Had to take care of other issues recently. So it's on my agenda starting today. I appreciate the extra eyes and analysis on this Issue.

KJ

**Comment by twopirllc** [comment] 2021-06-14 05:40
@AbyssAlora,

> Sorry guys, but I have no idea which version is right, if any 🙁

Don't feel bad! This is a known issue with **psar** even during TA Libs development. It's also an issue I have with the lack of standards regarding Technical Analysis indicators in general, platform and vendor variations make it difficult to say the least. _C'est la vie_!

```c
   /* Implementation of the SAR has been a little bit open to interpretation
    * since Wilder (the original author) did not define a precise algorithm
    * on how to bootstrap the algorithm. Take any existing software application
    * and you will see slight variation on how the algorithm was adapted.
    *
    * What is the initial trade direction? Long or short?
    * ===================================================
    * The interpretation of what should be the initial SAR values is
    * open to interpretation, particularly since the caller to the function
    * does not specify the initial direction of the trade.
    *
    * In TA-Lib, the following logic is used:
    *  - Calculate +DM and -DM between the first and
    *    second bar. The highest directional indication will
    *    indicate the assumed direction of the trade for the second
    *    price bar. 
    *  - In the case of a tie between +DM and -DM,
    *    the direction is LONG by default.
    *
    * What is the initial "extreme point" and thus SAR?
    * =================================================
    * The following shows how different people took different approach:
    *  - Metastock use the first price bar high/low depending of
    *    the direction. No SAR is calculated for the first price
    *    bar.
    *  - Tradestation use the closing price of the second bar. No
    *    SAR are calculated for the first price bar.
    *  - Wilder (the original author) use the SIP from the
    *    previous trade (cannot be implement here since the
    *    direction and length of the previous trade is unknonw).
    *  - The Magazine TASC seems to follow Wilder approach which
    *    is not practical here.
    *
    * TA-Lib "consume" the first price bar and use its high/low as the
    * initial SAR of the second price bar. I found that approach to be
    * the closest to Wilders idea of having the first entry day use
    * the previous extreme point, except that here the extreme point is
    * derived solely from the first price bar. I found the same approach
    * to be used by Metastock.
    */
```

<br/>

By any account, @AbyssAlora 's version certainly fixes the Issue @mtvu and I have noticed above. So that's a bonus! 🎉  I would make a PR with your changes so you can be added as a contributor. 😎 

<img width="881" alt="Screen Shot 2021-06-13 at 9 47 05 PM" src="https://user-images.githubusercontent.com/18198392/121840435-19328e80-cc91-11eb-85c8-e06aa83b28cf.png">

<br/>

<img width="553" alt="Screen Shot 2021-06-13 at 9 46 56 PM" src="https://user-images.githubusercontent.com/18198392/121840453-251e5080-cc91-11eb-852c-5bc5d81da76b.png">


<br/>

However, there is another Issue with how **psar** handles the initial values between TV, TA Lib, and Pandas TA. Just like outlined above in TA Lib. Sometimes TA Lib matches TV's from the 2nd row on and sometimes it doesn't like in this case:

<img width="876" alt="Screen Shot 2021-06-13 at 10 06 47 PM" src="https://user-images.githubusercontent.com/18198392/121841762-da520800-cc93-11eb-8b24-960b391ba56b.png">

<br/>

<img width="519" alt="Screen Shot 2021-06-13 at 10 06 36 PM" src="https://user-images.githubusercontent.com/18198392/121841792-e938ba80-cc93-11eb-8fd8-ba16fa966b98.png">

<br/>

Looking at the Daily TV charts of _$RKT_ and _$PLTR_, the initial **psar** is None/NaN for the 1s candlestick. For the 2nd candlestick, it could be either the prior high or low or perhaps the DM calculation as described above in TA Lib. If you want to figure out the **psar** for 2nd candlestick, that would be great to. 😎 

Thanks,
KJ

**Closed** 2021-06-20 17:34 UTC
Labels: bug, help wanted
