### ISSUE TITLE
param col_names for indicators with one resulting column

### ISSUE THREAD

**Issue by ganti** [twopirllc/pandas-ta#304] opened 2021-05-31 20:26 UTC
Some indicators return multiple columns, then it is possible to rename the returned columns with `col_names` but for indicators with just one column this is not working e.g. for kind wma

The renaming happens at https://github.com/twopirllc/pandas-ta/blob/b2f2cc83a16376c1eb0a11aebed52186d7eab121/pandas_ta/core.py#L406
but i cant seee why it should not work for indicators with just one resulting column

**Comment by twopirllc** [comment] 2021-05-31 21:31
Hello @ganti,

> but i cant seee why it should not work for indicators with just one resulting column

You are correct! I am guessing you are not using a ```tuples``` for the "col_names" since you provided no reproducible code.

<img width="789" alt="Screen Shot 2021-05-31 at 2 27 13 PM" src="https://user-images.githubusercontent.com/18198392/120243467-828bb980-c21c-11eb-9460-92690d340f3d.png">

If the above does not work for you, please provide some code so I can better assist you.

Kind Regards,
KJ

**Comment by ganti** [comment] 2021-06-01 16:47
Hi KJ,
Thanks for your answer! This solves it to me. But this revield an interesting case with tuples when there is just one element. 
`{'kind': 'ema', 'length': 18 , 'col_names':('ema',) }` -> renaming works, because comma after element
`{'kind': 'ema', 'length': 18 , 'col_names':('ema') } ` -> renaming not working, because python wont treat it as tuple

```python
t1 = ('xxx',)
print('with trailing comma',type(t1))

t2 = ('xxx')
print('without trailing comma',type(t2))
```
```
with trailing comma <class 'tuple'>
without trailing comma <class 'str'>
```

This is a general python issue. According to [TupleSyntax](https://wiki.python.org/moin/TupleSyntax): _The essential element here is the trailing comma._ 

IMO this should be fixed by python, but we could make it possible to convert it to a tuple if it is not:
https://github.com/twopirllc/pandas-ta/blob/b2f2cc83a16376c1eb0a11aebed52186d7eab121/pandas_ta/core.py#L406
```python
if "col_names" in kwargs:
    if not isinstance(kwargs["col_names"], tuple):
        kwargs["col_names"] = tuple(kwargs["col_names"])
```

**Comment by twopirllc** [comment] 2021-06-01 17:26
@ganti,

No worries.

> This is a general python issue. According to TupleSyntax: The essential element here is the trailing comma.

> IMO this should be fixed by python, but we could make it possible to convert it to a tuple if it is not

Yeah. That's a reasonable fix. I do not foresee any issues including it if you want to make a PR. Contributions are welcome. 😎 

Thanks,
KJ

**Comment by ganti** [comment] 2021-06-22 17:02
@twopirllc I tried fixing it, but could not do it,

It seems there is a `isinstance(kwargs["col_names"], tuple)` check before but didnt find out wich of the lines below must be changed as well to do the trick

https://github.com/twopirllc/pandas-ta/blob/b2f2cc83a16376c1eb0a11aebed52186d7eab121/pandas_ta/core.py#L418
https://github.com/twopirllc/pandas-ta/blob/b2f2cc83a16376c1eb0a11aebed52186d7eab121/pandas_ta/core.py#L707

**Comment by twopirllc** [comment] 2021-06-22 18:08
@ganti,

Ok. I'll reopen and set it as a Good First Issue.

KJ

**Comment by twopirllc** [comment] 2021-06-30 19:42
Hello @ganti,

It should be fixed now. It is on the _development_ branch if you want to check it out before I update _main_.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks,
KJ

**Comment by ganti** [comment] 2021-07-02 14:48
Hey @twopirllc 

I tested it and it works. Great job. I don't get why I could not get it working, since I tried what you did.
IMO ready to merge

**Comment by twopirllc** [comment] 2021-07-02 16:22
@ganti,

Thank you for taking the time to check and respond promptly. I appreciate it.

Thanks,
KJ

**Comment by twopirllc** [comment] 2021-07-02 17:08
@ganti,

It's available now on the _main_ branch or _pypi_. Please let me know if there are any issues.

Thanks,
KJ

**Closed** 2021-07-02 20:30 UTC
Labels: enhancement, good first issue, info
