### ISSUE TITLE
example.ipynb does not work

### ISSUE THREAD

**Issue by yhmickey** [twopirllc/pandas-ta#140] opened 2020-09-30 08:58 UTC
```
Chart(df,
    # style: which mplfinance chart style to use. Added "random" as an option.
    # rpad: how many bars to leave empty on the right of the chart
    style="yahoo", title=ticker, last=recent_bars(df), rpad=10,
    
    # Overlap Indicators
    linreg=True, midpoint=False, ohlc4=False, archermas=True,
    
    # Example Indicators with default parameters
    volume=True, rsi=True, clr=True, macd=True, zscore=False, squeeze=False, lazybear=False,

    # Archer OBV and OBV MAs (https://www.tradingview.com/script/Co1ksara-Trade-Archer-On-balance-Volume-Moving-Averages-v1/)
    archerobv=False,

    # Create trends and see their returns
    trendreturn=False,
    # Example Trends or create your own. Trend must yield Booleans
    long_trend=ta.sma(closedf,10) > ta.sma(closedf,20), # trend: sma(close,10) > sma(close,20) [Default Example]
#     long_trend=closedf > ta.ema(closedf,5), # trend: close > ema(close,5)
#     long_trend=ta.sma(closedf,10) > ta.ema(closedf,50), # trend: sma(close,10) > ema(close,50)
#     long_trend=macdh > 0, # trend: macd hist > 0
#     long_trend=ta.increasing(ta.sma(ta.rsi(closedf), 10), 5, asint=False), # trend: rising sma(rsi, 10) for the previous 5 periods
    show_nontrading=False, # Intraday use if needed
    verbose=True, # More detail
)
```

output:
```
[i] Loaded SPY(5262, 62)
[+] Strategy: Common Price and Volume SMAs
[i] Indicator arguments: {'append': True}
[i] Multiprocessing: 16 of 16 cores.
[i] Total indicators: 5
[i] Columns added: 0
D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\cbook\__init__.py:1377: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  x[:, None]
D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axes\_base.py:239: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  y = y[:, np.newaxis]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-44-f7c14830084c> in <module>
     26 #     long_trend=ta.increasing(ta.sma(ta.rsi(closedf), 10), 5, asint=False), # trend: rising sma(rsi, 10) for the previous 5 periods
     27     show_nontrading=False, # Intraday use if needed
---> 28     verbose=True, # More detail
     29 )

<ipython-input-35-df099406cc6a> in __init__(self, df, strategy, *args, **kwargs)
     20         # Build TA and Plot
     21         self.df.ta.strategy(self.strategy, verbose=self.verbose)
---> 22         self._plot(**kwargs)
     23 
     24     def _validate_ta_strategy(self, strategy):

<ipython-input-35-df099406cc6a> in _plot(self, **kwargs)
    340             show_nontrading=self.mpfchart["non_trading"],
    341             vlines=vlines_,
--> 342             addplot=taplots
    343         )
    344 

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\mplfinance\plotting.py in plot(data, **kwargs)
    610 
    611     if config['volume']:
--> 612         volumeAxes.figure.canvas.draw()  # This is needed to calculate offset
    613         offset = volumeAxes.yaxis.get_major_formatter().get_offset()
    614         volumeAxes.yaxis.offsetText.set_visible(False)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    400         toolbar = self.toolbar
    401         try:
--> 402             self.figure.draw(self.renderer)
    403             # A GUI class may be need to update a window using this draw, so
    404             # don't forget to call the superclass.

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1647 
   1648             mimage._draw_list_compositing_images(
-> 1649                 renderer, self, artists, self.suppressComposite)
   1650 
   1651             renderer.close_group('figure')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2626             renderer.stop_rasterizing()
   2627 
-> 2628         mimage._draw_list_compositing_images(renderer, self, artists)
   2629 
   2630         renderer.close_group('axes')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in draw(self, renderer, *args, **kwargs)
   1183         renderer.open_group(__name__)
   1184 
-> 1185         ticks_to_draw = self._update_ticks(renderer)
   1186         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1187                                                                 renderer)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in _update_ticks(self, renderer)
   1021 
   1022         interval = self.get_view_interval()
-> 1023         tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
   1024         if self._smart_bounds and tick_tups:
   1025             # handle inverted limits

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in iter_ticks(self)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\mplfinance\_utils.py in __call__(self, x, pos)
   1135         else:
   1136             date = self.dates[ix]
-> 1137             dateformat = mdates.num2date(date).strftime(self.fmt)
   1138         #print('x=',x,'pos=',pos,'dates[',ix,']=',date,'dateformat=',dateformat)
   1139         return dateformat

ValueError: Invalid format string

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2047                         orientation=orientation,
   2048                         dryrun=True,
-> 2049                         **kwargs)
   2050                     renderer = self.figure._cachedRenderer
   2051                     bbox_artists = kwargs.pop("bbox_extra_artists", None)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backends\backend_agg.py in print_png(self, filename_or_obj, *args, **kwargs)
    508 
    509         """
--> 510         FigureCanvasAgg.draw(self)
    511         renderer = self.get_renderer()
    512 

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    400         toolbar = self.toolbar
    401         try:
--> 402             self.figure.draw(self.renderer)
    403             # A GUI class may be need to update a window using this draw, so
    404             # don't forget to call the superclass.

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1647 
   1648             mimage._draw_list_compositing_images(
-> 1649                 renderer, self, artists, self.suppressComposite)
   1650 
   1651             renderer.close_group('figure')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2626             renderer.stop_rasterizing()
   2627 
-> 2628         mimage._draw_list_compositing_images(renderer, self, artists)
   2629 
   2630         renderer.close_group('axes')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in draw(self, renderer, *args, **kwargs)
   1183         renderer.open_group(__name__)
   1184 
-> 1185         ticks_to_draw = self._update_ticks(renderer)
   1186         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1187                                                                 renderer)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in _update_ticks(self, renderer)
   1021 
   1022         interval = self.get_view_interval()
-> 1023         tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
   1024         if self._smart_bounds and tick_tups:
   1025             # handle inverted limits

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in iter_ticks(self)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\mplfinance\_utils.py in __call__(self, x, pos)
   1135         else:
   1136             date = self.dates[ix]
-> 1137             dateformat = mdates.num2date(date).strftime(self.fmt)
   1138         #print('x=',x,'pos=',pos,'dates[',ix,']=',date,'dateformat=',dateformat)
   1139         return dateformat

ValueError: Invalid format string

<Figure size 1200x1000 with 10 Axes>
```

**Comment by twopirllc** [comment] 2020-09-30 14:49
Hello @yhmickey,

Thanks for trying **Pandas TA**!

Why did you delete all the bug questions? They are there for me to help you diagnose and quickly resolve your issue. So please answer them **soon** before I close this issue.

1. **Which version are you running?**
Run the following to find out and tell me:
```python
import pandas_ta as ta
print(ta.version)
```

2. **To Reproduce**
Where is the code? What did you do up to and include running ```Chart(df, ....)```?

3. **Screenshots**
Show me! Give me something to figure it out.

So ```example.ipynb does not work```?

Did it work the **_first_** time before you modified your ```df``` to have a multiindex? Because I guarantee that it _did_ work.

It is clear that you modified your ```df``` since the _first_ error says: ```FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated ...``` from the ```matplotlib``` package. It **is** a ```matplotlib``` error via ```mplfinance``` and **not** a **Pandas TA** error. Before running ```Chart(df, ...)```, your ```df``` already had columns, ```[i] Loaded SPY(5262, 62)```, meaning you modified ```df``` to have a multiindex somewhere along the way before. Where is that code? What did you do up to and include running ```Chart(df, ....)```? Show me! Give me something to figure it out.

Are the other indexes of your multiindex ```df``` other symbols or tickers, like _SPY_, _AAPL_, _TSLA_, ... ?  If so, ```mplfinance``` is freaking out and quits.

Regards,
KJ

**Comment by yhmickey** [comment] 2020-09-30 20:34
Hello @twopirllc ,
Thank you for your prompt reply !

1.  ta.version is 0.2.15b0.

2. I just clone the code and run the example.ipynb in examples . I execute the code sequentially. I did not input any personal code.

3. Here is the screenshot and errors.
![1](https://user-images.githubusercontent.com/34559558/94736552-01cfa180-039f-11eb-8653-49202c1ac8c4.JPG)
![2](https://user-images.githubusercontent.com/34559558/94736559-03996500-039f-11eb-9d63-86d36fe0d05b.JPG)
![3](https://user-images.githubusercontent.com/34559558/94736564-05632880-039f-11eb-8358-b2bc6132eb90.JPG)
![4](https://user-images.githubusercontent.com/34559558/94736569-06945580-039f-11eb-9300-d2f9504d8611.JPG)
![5](https://user-images.githubusercontent.com/34559558/94736570-072cec00-039f-11eb-9ea8-0029245ef02c.JPG)
![6](https://user-images.githubusercontent.com/34559558/94736571-07c58280-039f-11eb-8920-7dcc40470c41.JPG)
![7](https://user-images.githubusercontent.com/34559558/94736573-085e1900-039f-11eb-8196-75e574705eea.JPG)
![8](https://user-images.githubusercontent.com/34559558/94736577-08f6af80-039f-11eb-871b-8d3f37400d19.JPG)
'''
[i] Loaded SPY(5262, 33)
[+] Strategy: Common Price and Volume SMAs
[i] Indicator arguments: {'append': True}
[i] Multiprocessing: 16 of 16 cores.
[i] Total indicators: 5
[i] Columns added: 5
D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\cbook\__init__.py:1377: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  x[:, None]
D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axes\_base.py:239: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  y = y[:, np.newaxis]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-f7c14830084c> in <module>
     26 #     long_trend=ta.increasing(ta.sma(ta.rsi(closedf), 10), 5, asint=False), # trend: rising sma(rsi, 10) for the previous 5 periods
     27     show_nontrading=False, # Intraday use if needed
---> 28     verbose=True, # More detail
     29 )

<ipython-input-12-df099406cc6a> in __init__(self, df, strategy, *args, **kwargs)
     20         # Build TA and Plot
     21         self.df.ta.strategy(self.strategy, verbose=self.verbose)
---> 22         self._plot(**kwargs)
     23 
     24     def _validate_ta_strategy(self, strategy):

<ipython-input-12-df099406cc6a> in _plot(self, **kwargs)
    340             show_nontrading=self.mpfchart["non_trading"],
    341             vlines=vlines_,
--> 342             addplot=taplots
    343         )
    344 

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\mplfinance\plotting.py in plot(data, **kwargs)
    610 
    611     if config['volume']:
--> 612         volumeAxes.figure.canvas.draw()  # This is needed to calculate offset
    613         offset = volumeAxes.yaxis.get_major_formatter().get_offset()
    614         volumeAxes.yaxis.offsetText.set_visible(False)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    400         toolbar = self.toolbar
    401         try:
--> 402             self.figure.draw(self.renderer)
    403             # A GUI class may be need to update a window using this draw, so
    404             # don't forget to call the superclass.

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1647 
   1648             mimage._draw_list_compositing_images(
-> 1649                 renderer, self, artists, self.suppressComposite)
   1650 
   1651             renderer.close_group('figure')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2626             renderer.stop_rasterizing()
   2627 
-> 2628         mimage._draw_list_compositing_images(renderer, self, artists)
   2629 
   2630         renderer.close_group('axes')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in draw(self, renderer, *args, **kwargs)
   1183         renderer.open_group(__name__)
   1184 
-> 1185         ticks_to_draw = self._update_ticks(renderer)
   1186         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1187                                                                 renderer)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in _update_ticks(self, renderer)
   1021 
   1022         interval = self.get_view_interval()
-> 1023         tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
   1024         if self._smart_bounds and tick_tups:
   1025             # handle inverted limits

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in iter_ticks(self)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\mplfinance\_utils.py in __call__(self, x, pos)
   1135         else:
   1136             date = self.dates[ix]
-> 1137             dateformat = mdates.num2date(date).strftime(self.fmt)
   1138         #print('x=',x,'pos=',pos,'dates[',ix,']=',date,'dateformat=',dateformat)
   1139         return dateformat

ValueError: Invalid format string

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2047                         orientation=orientation,
   2048                         dryrun=True,
-> 2049                         **kwargs)
   2050                     renderer = self.figure._cachedRenderer
   2051                     bbox_artists = kwargs.pop("bbox_extra_artists", None)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backends\backend_agg.py in print_png(self, filename_or_obj, *args, **kwargs)
    508 
    509         """
--> 510         FigureCanvasAgg.draw(self)
    511         renderer = self.get_renderer()
    512 

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    400         toolbar = self.toolbar
    401         try:
--> 402             self.figure.draw(self.renderer)
    403             # A GUI class may be need to update a window using this draw, so
    404             # don't forget to call the superclass.

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\figure.py in draw(self, renderer)
   1647 
   1648             mimage._draw_list_compositing_images(
-> 1649                 renderer, self, artists, self.suppressComposite)
   1650 
   1651             renderer.close_group('figure')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axes\_base.py in draw(self, renderer, inframe)
   2626             renderer.stop_rasterizing()
   2627 
-> 2628         mimage._draw_list_compositing_images(renderer, self, artists)
   2629 
   2630         renderer.close_group('axes')

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     48                 renderer.start_filter()
     49 
---> 50             return draw(artist, renderer, *args, **kwargs)
     51         finally:
     52             if artist.get_agg_filter() is not None:

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in draw(self, renderer, *args, **kwargs)
   1183         renderer.open_group(__name__)
   1184 
-> 1185         ticks_to_draw = self._update_ticks(renderer)
   1186         ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
   1187                                                                 renderer)

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in _update_ticks(self, renderer)
   1021 
   1022         interval = self.get_view_interval()
-> 1023         tick_tups = list(self.iter_ticks())  # iter_ticks calls the locator
   1024         if self._smart_bounds and tick_tups:
   1025             # handle inverted limits

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in iter_ticks(self)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\matplotlib\axis.py in <listcomp>(.0)
    969         self.major.formatter.set_locs(majorLocs)
    970         majorLabels = [self.major.formatter(val, i)
--> 971                        for i, val in enumerate(majorLocs)]
    972 
    973         minorLocs = self.minor.locator()

D:\ProgramData\Anaconda3\envs\vnpy\lib\site-packages\mplfinance\_utils.py in __call__(self, x, pos)
   1135         else:
   1136             date = self.dates[ix]
-> 1137             dateformat = mdates.num2date(date).strftime(self.fmt)
   1138         #print('x=',x,'pos=',pos,'dates[',ix,']=',date,'dateformat=',dateformat)
   1139         return dateformat

ValueError: Invalid format string

<Figure size 1200x1000 with 10 Axes>
'''

Thank you for your help. Your work is very valuable！
Regards,
YH

**Comment by twopirllc** [comment] 2020-09-30 21:43
@yhmickey,

> ta.version is 0.2.15b0.

Thank you

> Here is the screenshot and errors.

Thank you for providing some screenshots of what you have done. It helps a **lot**. This time is mildly different since ```df``` actually added columns and you have _32_ columns instead of _62_ columns.

What version of ```mplfinance``` are you using? Perhaps you have an older ```mplfinance``` or ```matplotlib```?

Here is how to find the version info of all the required packages:
<img width="1022" alt="Screen Shot 2020-09-30 at 2 40 01 PM" src="https://user-images.githubusercontent.com/18198392/94742662-ed51c180-032a-11eb-9da6-16c413529b2b.png">

Here are the versions used in ```example``` Notebook. At least these versions or greater are preferred.
<img width="982" alt="Screen Shot 2020-09-30 at 2 38 58 PM" src="https://user-images.githubusercontent.com/18198392/94742750-0fe3da80-032b-11eb-95b2-0295a2ae45f5.png">

Thanks,
KJ

**Comment by yhmickey** [comment] 2020-10-01 01:01
@twopirllc ,
Here are the versions used in my Notebook.
![1111](https://user-images.githubusercontent.com/34559558/94754696-8254c900-03c4-11eb-96ea-86072e66617a.JPG)

Thanks
YH

**Comment by twopirllc** [comment] 2020-10-02 20:06
Hello @yhmickey,

I assume by no response that the solution provided solved the issue. Thus I will be closing this issue in a few days.

Thanks,
KJ

**Comment by yhmickey** [comment] 2020-10-02 20:46
Hello @twopirllc 
I have updated the matplotlib to the newest v3.3.2, but it doesn't work. I guest the key of the problem is the version of the pandas_ta .

1. I can not find your version of pandas_ta by using pip. Here are the versions.
![1](https://user-images.githubusercontent.com/34559558/94967236-41c68e00-0531-11eb-9272-f9e75416a5cb.JPG)

2. I reinstall pandas_ta using pip .The version is 0.1.97. Here is the problem.
![2](https://user-images.githubusercontent.com/34559558/94967711-2d36c580-0532-11eb-84d7-23255ab17681.JPG)

3. I reinstall pandas_ta using git. The version is 0.2.15b0. The problem is cell 13 is still the same.
![3](https://user-images.githubusercontent.com/34559558/94967746-4770a380-0532-11eb-9c57-33706ab547d8.JPG)

4. Here are the screenshots of all cells.

![4](https://user-images.githubusercontent.com/34559558/94968256-2c526380-0533-11eb-832b-1f77f90eca8d.JPG)
![5](https://user-images.githubusercontent.com/34559558/94968262-2e1c2700-0533-11eb-8614-5656923e1a9c.JPG)
![6](https://user-images.githubusercontent.com/34559558/94968263-2f4d5400-0533-11eb-8a50-3c7c258a021f.JPG)
![7](https://user-images.githubusercontent.com/34559558/94968268-2fe5ea80-0533-11eb-99a0-dfb6d7beb94a.JPG)
![8](https://user-images.githubusercontent.com/34559558/94968270-307e8100-0533-11eb-8f28-4effb1a46799.JPG)
![9](https://user-images.githubusercontent.com/34559558/94968271-31afae00-0533-11eb-8ee0-af8f83b97ff5.JPG)
![10](https://user-images.githubusercontent.com/34559558/94968276-32484480-0533-11eb-9918-e6ed001607b6.JPG)


Thank you. Hope these message can help.
YH

**Comment by twopirllc** [comment] 2020-10-04 16:23
@yhmickey,

Thanks for the updates and screenshots. I have somethings to finish before updating the main Github version. Then we can try again with the new Github version. I'll let you know when the main version is ready.

Thanks,
KJ

**Comment by twopirllc** [comment] 2020-10-04 23:39
Hello @yhmickey,

Just updated Github with a new version.

```sh
$ pip uninstall pandas_ta
$ pip install -U git+https://github.com/twopirllc/pandas-ta
```

Please keep me informed on that status. Also, have you tried a fresh install in a new directory?

Thanks,
KJ

**Comment by yhmickey** [comment] 2020-10-05 14:02
@twopirllc 
Thank you. I love pandas_ta. It is a great job. This issue is not a big problem. 

I have tried the new version of pandas_ta and mplfinance , but the problem is still the same.

But it doesn't matter.  This does not affect my learning how to use it.

Thank you for your pandas_ta.

**Comment by twopirllc** [comment] 2020-10-05 14:43
@yhmickey,

Thanks. Other than charting not working for some reason, is the library easy to use and working?

Thanks,
KJ

**Comment by yhmickey** [comment] 2020-10-05 16:43
@twopirllc 

Yes, it is very easy to use and working.

Thanks.
YH

**Comment by twopirllc** [comment] 2020-10-05 18:42
@yhmickey,

Great! Glad to hear.

Regards,
KJ

**Closed by twopirllc** 2020-10-05 18:42 UTC
Labels: info, question
