### ISSUE TITLE
Supertrend indicator giving only short values

### ISSUE THREAD

**Issue by Jacks349** [twopirllc/pandas-ta#116] opened 2020-09-06 13:54 UTC
This is not a bug report, because i'm pretty sure it has to do with the OHLC data i'm feeding to pandas-ta. 

I noticed that with some markets i'll get only short values, so on the chart the band will be red for the whole length of the chart itself. This "issue" seems to happen when i set an higher Accelerator, in this case i'm setting it to 4. What is weird to me, is that this won't happen with some other markets, with the same amount of candles (1550). 

![q](https://user-images.githubusercontent.com/65462643/92327228-717c9600-f058-11ea-915a-4260d0e984bc.png)
 
Could it be because i don't have enough data to let the ATR be calculated properly?

Here is my code, to replicate my issue:
```python
import pandas as pd
import cfscrape
import pandas_ta as ta
import numpy as np
import json, datetime

BU = cfscrape.create_scraper()

URL = "https://api.binance.com/api/v1/klines?&symbol=TRXBTC&interval=4h&limit=1550"

ResultRaw = BU.get(URL, timeout=(10, 15)).content
Result = json.loads(ResultRaw)

for x in Result:
    TimeUnix = float(x[0]) / float(1000)
    K = datetime.datetime.fromtimestamp(TimeUnix)
    x[0] = K

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

df = pd.DataFrame([x[:6] for x in Result], 
                  columns=['Date', 'Open', 'High', 'Low', 'Close', 'Volume'])


format = '%Y-%m-%d %H:%M:%S'
df['Date'] = pd.to_datetime(df['Date'], format=format)
df = df.set_index(pd.DatetimeIndex(df['Date']))
df["Open"] = pd.to_numeric(df["Open"],errors='coerce')
df["High"] = pd.to_numeric(df["High"],errors='coerce')
df["Low"] = pd.to_numeric(df["Low"],errors='coerce')
df["Close"] = pd.to_numeric(df["Close"],errors='coerce')
df["Volume"] = pd.to_numeric(df["Volume"],errors='coerce')

df = df.fillna(value=0)

df = df.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Close': 'close', 'Volume': 'Volume'})
ST = ta.supertrend(df['high'], df['low'], df['close'], 10, 4.0)

print(ST)
```

**Comment by twopirllc** [comment] 2020-09-06 17:49
Hi @Jacks349,

I'll tack it onto the issues to look into.

Based on a quick glance, and I am not sure if it will solve the issue, but have you tried:
```python
ST = ta.supertrend(df['high'], df['low'], df['close'], length=10 multiplier=4.0)
print(ST)
```

Also since you are using a DataFrame, _df_, have you tried using the DataFrame extension ```ta```? You wouldn't have to include: ```df['high'], df['low'], df['close']```
```python
ST = df.ta.supertrend(length=10, multiplier=4.0)
print(ST)

# If you want to append the results of Super Trend onto df, you can do:
df.ta.supertrend(length=10, multiplier=4.0, append=True)
print(df)
```

Hope this helps!
KJ

**Comment by Jacks349** [comment] 2020-09-06 21:22
> Hi @Jacks349,
> 
> I'll tack it onto the issues to look into.
> 
> Based on a quick glance, and I am not sure if it will solve the issue, but have you tried:
> 
> ```python
> ST = ta.supertrend(df['high'], df['low'], df['close'], length=10 multiplier=4.0)
> print(ST)
> ```
> 
> Also since you are using a DataFrame, _df_, have you tried using the DataFrame extension `ta`? You wouldn't have to include: `df['high'], df['low'], df['close']`
> 
> ```python
> ST = df.ta.supertrend(length=10, multiplier=4.0)
> print(ST)
> 
> # If you want to append the results of Super Trend onto df, you can do:
> df.ta.supertrend(length=10, multiplier=4.0, append=True)
> print(df)
> ```
> 
> Hope this helps!
> KJ

Thank you a lot for taking your time to answer! Using the `ta` extension made it way easier to read, thank you for the advice! I tried to set `length=10, multiplier=4.0` but the output was the same. If on `URL` i change `TRXBTC` to `BTCUSDT` the output will be different: only the first part of the chart will be "always red", while the rest is normal, so i'm assuming this could be because i'm not giving it enough candles to calculate, or on `TRXBTC` the very low magnitude of my data (prices are very low) might give problems when calculating the ATR

**Comment by twopirllc** [comment] 2020-09-14 18:32
Hello @Jacks349,

I apologize for the delay. Been swamped. Anyhow I finally took a gander at this and reworked some of your code which you thankfully provided 😎 .

```python
# Helper Methods
def to_dt(data: list):
    for x in data:
        x[0] = datetime.datetime.fromtimestamp(float(x[0]) / float(1000)) # update first element
    return data

def to_df(data: list, dt_format: str = "%Y-%m-%d %H:%M:%S"):
    data = to_dt(data)
    df = pd.DataFrame([x[:6] for x in data])
    df.columns = ["date", "open", "high", "low", "close", "volume"]

    df.set_index(pd.DatetimeIndex(df["date"]), inplace=True)
    df.drop("date", axis=1, inplace=True)
    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
    df.fillna(value=0, inplace=True)
    return df

# Fetch and Clean
COINURL = "https://api.binance.com/api/v1/klines?&symbol=TRXBTC&interval=4h&limit=1550"
BU = cfscrape.create_scraper()
raw_result = BU.get(COINURL, timeout=(10, 15)).content
df = to_df(json.loads(raw_result))

# SupaTrend & Plot
st = df.ta.supertrend(length=10, multiplier=4.0, append=True)
st["close"] = df.close
st[st.columns[-3:]].plot(figsize=(16, 8), color=["green", "red", "black"], grid=True)
```

I am not seeing an issue in plotting and seems to show both long and short regime changes. At first I thought it was also the magnitude of the values impacting the results, but that appears not to be the case thankfully.

Here is the chart I have after running the code I have supplied above. Please try it out and let me know if anything is different or if you are still encountering this issue.

<img width="867" alt="Screen Shot 2020-09-14 at 11 28 49 AM" src="https://user-images.githubusercontent.com/18198392/93123806-8622e480-f67d-11ea-9958-ca75e1f88073.png">

Hope this helps!
KJ

**Comment by Davxyp** [comment] 2020-09-15 08:37
@twopirllc 
Thank you a lot for your answer and thank you even more for improving my code! Now i'm sure that the problem is on my side and not on P_TA's side. I tried the **exact** same code and i got the following output:

![q](https://user-images.githubusercontent.com/47790276/93185945-51c32d00-f73e-11ea-9278-ee73da214253.png)

I really don't know what's going on here, i was thinking that maybe some module is not updated or something is conflicting with pandas.

**Comment by twopirllc** [comment] 2020-09-15 16:30
@Davxyp,

> Thank you a lot for your answer and thank you even more for improving my code!

No worries. Thanks for your patience.

> Now i'm sure that the problem is on my side and not on P_TA's side. I tried the exact same code...

That is weird! Did you encounter any errors that you had to correct when running the code? Is there any other code around that block that you think may be interfering with it somehow?

What does the DataFrame ```df``` look like prior to running ```supertrend```?
```python
df = to_df(json.loads(raw_result))
print(df.info())
df
```

Unfortunately, I can not do much on this end. However you can also edit/tinker your local ```supertrend.py``` file in the _overlap_ directory and see if ```long[i]``` is storing anything in the _for loop_. Please keep me posted on what you are able to discover. Hopefully it is something trivially wrong outside of ```supertrend.py```.

Thanks,
KJ

**Comment by Davxyp** [comment] 2020-09-15 17:39
@twopirllc 
Yes, as soon as i have enough time i'm going to do a full check on my modules, try to reinstall some stuff and see what happens. In the meantime, If it's ok for you, you can close the issue since we saw that the problem is not with the library itself but on my side.

Thank you a lot for your help!

**Comment by twopirllc** [comment] 2020-09-15 17:44
@Davxyp,

No worries. Keep me posted.

Thanks,
KJ

**Closed by twopirllc** 2020-09-15 17:44 UTC

**Comment by sadunalpdag** [comment] 2022-02-20 17:06
hello

I have an error for the super trend indicator

can't multiply sequence by non-int of type 'float'

thanks

**Comment by twopirllc** [comment] 2022-02-20 18:55
Hello @sadunalpdag,

Please fill out a new [Issue](https://github.com/twopirllc/pandas-ta/issues/new/choose) and not piggyback on an old closed issue that appears to not be related to original Issue here. Furthermore, please be as **verbose** as possible as requested in the Issue Form.

For instance, this is not helpful for me to help you... 
> can't multiply sequence by non-int of type 'float'

Kind Regards,
KJ
