### ISSUE TITLE
stdev does not take ddof = 0

### ISSUE THREAD

**Issue by dnabb** [twopirllc/pandas-ta#354] opened 2021-07-26 13:51 UTC
**Which version are you running? The lastest version is on Github. Pip is for major releases.**
0.3.2b0

**Describe the bug**
Calling stdev with ddof=0 (and all other derived indicator, like bbands) actually returns a standard deviation with ddof = 1.

**To Reproduce**

```python
import pandas as pd
import pandas_ta as ta

data = {'close': ['1', '2', '2', '1']}
df = pd.DataFrame.from_dict(data)

df.ta.stdev(length=4, ddof=0)[3] # Shoukd be 0.5

df.ta.stdev(length=4, ddof=0).equals(df.ta.stdev(length=4, ddof=1)) # Should be False
```

**Expected behavior**
Should be the same as:

```python
df.rolling(window=4).std(ddof=0)['close']
```

**Additional context**
The issue seems to be [this validation](https://github.com/twopirllc/pandas-ta/blob/1deb7559f626d2a5cf664b6c0af7a8016a53bfca/pandas_ta/statistics/stdev.py#L12) which fails with ddof = 0.

**Comment by twopirllc** [comment] 2021-07-26 16:34
Hello @dnabb,

Doh! Nice catch!

In the mean time, edit your local copy and replace that validation with the following until the code is updated.
```python
ddof = int(ddof) if isinstance(ddof, int) and ddof >= 0 and ddof < length else 1
```

Hope this helps!

Kind Regards,
KJ

**Comment by twopirllc** [comment] 2021-07-26 17:36
@dnabb,

Also I have added the changes to the _development_ branch if you want to test it out.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Please let me know if it works as intended if you try the _development_ branch.

Thanks,
KJ

**Comment by twopirllc** [comment] 2021-07-28 20:59
Hello @dnabb,

New stable version _v0.3.14b_ should help resolve this Issue. Please let me know otherwise.

```sh
$ pip install pandas_ta
```

Thanks,
KJ

**Comment by twopirllc** [comment] 2021-07-31 19:04
Hello @dnabb,

I assume by no response that the solution provided was sufficient. Thus I will be closing this issue in a few days.

Kind Regards,
KJ

**Comment by twopirllc** [comment] 2021-08-04 18:44
Hello @dnabb,

This should be fixed now. If you can test it out on the _development_ branch and let me know, that would be great.

```sh
$ pip install -U git+https://github.com/twopirllc/pandas-ta.git@development
```

Thanks
KJ

**Comment by dnabb** [comment] 2021-08-05 11:51
Hello @twopirllc ,

I can confirm the issue seems to be solved in 0.3.18b0.

**Closed** 2021-08-05 15:12 UTC
Labels: bug

**Comment by krazykoder** [comment] 2022-06-14 01:36
Just reopening this post. I observed TALIB `STDDEV` and pandas_ta `std_dev` generates different output. A reference to this issue is noted here as well https://github.com/mrjbq7/ta-lib/issues/69#issuecomment-901135607

But I just wanted to confirm with others that pandas_ta standard deviation should be safe to use right since it matches my final indicator calculations cross referencing tradingview. I will stop using talib for this function.

code to try below 
```
length=100, fast=50, slow=50

import talib as talib
talib.STDDEV(closeSeries, timeperiod=fast)

2022-06-08 12:00:00    12.704822
2022-06-09 08:00:00    12.060018
2022-06-09 12:00:00    10.837907
2022-06-10 08:00:00    10.635564
2022-06-10 12:00:00    10.512141
Length: 2038, dtype: float64
```

```
import pandas_ta as ta

ta.stdev(closeSeries, fast)

2022-06-08 12:00:00    12.833808
2022-06-09 08:00:00    12.182457
2022-06-09 12:00:00    10.947939
2022-06-10 08:00:00    10.743542
2022-06-10 12:00:00    10.618866
Name: STDEV_50, Length: 2038, dtype: float64
```

**Comment by krazykoder** [comment] 2022-06-14 04:18
Closing this issue, I found the answer in the same talib post (did not read fully sorry!) 

While using TALIB need to add `nbdev` parameter which is `np.sqrt(length / (length - 1)`
```
talib.STDDEV(closeSeries * 2, timeperiod=fast, nbdev=np.sqrt(fast / (fast - 1))
```
